var app=angular.module("app");
app.config(function($stateProvider,$urlRouterProvider){
    $urlRouterProvider.otherwise("/");
    $urlRouterProvider.when("/","//index");
    $urlRouterProvider.when("//licai","//licai/zhaiquan");
    $stateProvider
        .state("home",{
            url:"/",
            templateUrl:"views/home.html"
        })
        .state("home.index",{
            url:"/index",
            templateUrl:"views/index.html",
            controller:"index"
        })
        .state("home.licai",{
            url:"/licai",
            templateUrl:"views/licai.html",
            controller:"licai"
        })
        .state("home.licai.zhaiquan",{
            url:"/zhaiquan",
            templateUrl:"views/zhaiquan.html",
            controller:"zhaiquan"
        })
        .state("home.licai.jijin",{
            url:"/jijin",
            templateUrl:"views/jijin.html",
            controller:"jijin"
        })
        .state("home.user",{
            url:"/user",
            templateUrl:"views/user.html",
            controller:"user"
        })
        .state("home.more",{
            url:"/more",
            templateUrl:"views/more.html",
            controller:"more"
        })
});